---
# tasks file for vector-role
- name: Get_vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    validate_certs: false
    use_proxy: false
- name: Install vector
  become: true
  ansible.builtin.yum:
    name: "./vector-{{ vector_version }}-1.x86_64.rpm"
    disable_gpg_check: true
- name: Deploy Vector configuration
  become: true
  ansible.builtin.template:
    src: templates/config.yml.j2
    dest: /etc/vector/vector.yml
    mode: '0644'
  notify:
    - Start vector service
